# Gunakan image Node.js versi terbaru
FROM node:18-alpine

# Set direktori kerja
WORKDIR /app

# Copy file package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy seluruh kode ke container
COPY . .

# Set environment variable (opsional)
ENV PORT=8080

# Jalankan aplikasi
CMD ["node", "index.js"]
